name: pro_dialog
description: A beautiful animated customizable Flutter dialog package.
version: 1.0.0
homepage: https://github.com/AmirBayat0/pro_dialog
repository: https://github.com/AmirBayat0/pro_dialog
issue_tracker: https://github.com/AmirBayat0/pro_dialog/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
  
topics:
  - dialog
  - animation
  - ui
  - flutter
  - widgets

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0